data_dir: data

seed: 42

task_name: agrr
bert_model: bert-base-multilingual-cased
output_dir: output/final
validation_interval: 300

train_file: full.csv
train_batch_size: 32
accumulation_iters: 1

dev_file: dev.csv
dev_batch_size: 32

max_seq_length: 128
do_lower_case: False

num_workers: 2

learning_rate: 0.00001

train_stages:

    order: [train_head, finetune_1, finetune_2]

    train_head:
        groups: [sentence_classifier, full_annotation_classifier]
        num_cycles: 1
        epochs: 2
        learning_rate: 0.001
        warmup_ratio: 0.2

    finetune_1:
        num_cycles: 2
        epochs: 2
        learning_rate: 0.00002
        warmup_ratio: 0.1

    finetune_2:
        num_cycles: 2
        epochs: 3
        learning_rate: 0.000002
        warmup_ratio: 0.3
